version: "3.8"
services:
  database:
    image: postgres:latest
    container_name: go-backend-db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5433"
    volumes:
      - dbdata:/var/lib/postgres/data/
  server:
    container_name: go-backend-demo
    build:
      context: .
    env_file:
      - .env
    networks:
      - default   # default bridge network
    ports:
      - "8080:8080"
    depends_on:
      - database
volumes:
  dbdata:

